# Generated by Django 5.2.5 on 2025-08-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.RenameField(
            model_name='mealpreference',
            old_name='breakfast',
            new_name='selected',
        ),
        migrations.AddField(
            model_name='mealpreference',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meal_preferences', to='hotel_listing.meal'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mealpreference',
            unique_together={('booking', 'meal')},
        ),
        migrations.RemoveField(
            model_name='mealpreference',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='mealpreference',
            name='lunch',
        ),
    ]
