# Generated by Django 5.2.5 on 2025-08-17 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_listing', '0002_meal_rename_breakfast_mealpreference_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='primary_guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel_listing.guest'),
        ),
    ]
