# Generated by Django 5.2.5 on 2025-08-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_listing', '0004_alter_guest_managers_guest_date_joined_guest_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guest',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='password',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='username',
        ),
    ]
